[package]
name = "rbatis"
version = "1.0.7"
description = "Rust ORM Framework High Performance高性能Rust ORM框架(JSON based)"
readme = "Readme.md"
authors = ["ce <zhuxiujia@qq.com>"]
edition = "2018"
license = "MIT"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
xml-rs = "0.8"
lazy_static = "1.4.0"

#serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

#async
async-std = {version="1.3.0",features = ["attributes"] }

uuid = { version = "0.8", features = ["serde", "v4"] }
log = "0.4"
fast_log = "1.0.3"
#sql drivers
rbatis_drivers = "1.0.1"

#web library
actix-web = "2.0"
actix-rt = "1.0"
tokio = { version = "0.2", features = ["full"] }
hyper = "*"