[package]
name = "RustMybatis"
version = "0.1.0"
authors = ["ce <zhuxiujia@qq.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
xml-rs = "0.8"


serde = { version = "1.0", features = ["derive"] }
# serde_json is just for the example, not required in general
serde_json = "1.0"

#sql drivers
mysql="*"
postgres = "*"